### ISSUE TITLE
Generation without entering a prompt

### ISSUE THREAD

**Issue by muratsu** [fal-ai/interactive-3d-demo-app#1]
I shouldn't be allowed to hit generate without entering a prompt or it should pick up the placeholder prompt if nothing is submitted.

<img width="634" alt="image" src="https://github.com/fal-ai/interactive-3d-demo-app/assets/1308560/adfe4b0b-b6f2-424a-80e4-575bf719b2fe">
<img width="511" alt="image" src="https://github.com/fal-ai/interactive-3d-demo-app/assets/1308560/0de50857-e3e3-473b-9629-6f0acb9e4184">

**Comment by aykutkardas** [comment]
Fixed! ✅  Thanks for your feedback. ✨
